[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi[standard]>=0.115.11",
    "loguru>=0.7.3",
    "pydantic-settings>=2.8.1",
    "sqlalchemy>=2.0.38",
]
